/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GameType = { 'typingGame' : null } |
  { 'memoryGame' : null };
export interface Score {
  'scoreValue' : bigint,
  'playerName' : string,
  'gameType' : GameType,
}
export interface _SERVICE {
  'addFunFact' : ActorMethod<[string], undefined>,
  'addScore' : ActorMethod<[string, bigint, GameType], string>,
  'getAllFunFacts' : ActorMethod<[], Array<string>>,
  'getFactByIndex' : ActorMethod<[bigint], string>,
  'getPlayerBestScore' : ActorMethod<[string, GameType], [] | [Score]>,
  'getTopScores' : ActorMethod<[GameType], Array<Score>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];