/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameType = IDL.Variant({
  'typingGame' : IDL.Null,
  'memoryGame' : IDL.Null,
});
export const Score = IDL.Record({
  'scoreValue' : IDL.Nat,
  'playerName' : IDL.Text,
  'gameType' : GameType,
});

export const idlService = IDL.Service({
  'addFunFact' : IDL.Func([IDL.Text], [], []),
  'addScore' : IDL.Func([IDL.Text, IDL.Nat, GameType], [IDL.Text], []),
  'getAllFunFacts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFactByIndex' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getPlayerBestScore' : IDL.Func(
      [IDL.Text, GameType],
      [IDL.Opt(Score)],
      ['query'],
    ),
  'getTopScores' : IDL.Func([GameType], [IDL.Vec(Score)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameType = IDL.Variant({
    'typingGame' : IDL.Null,
    'memoryGame' : IDL.Null,
  });
  const Score = IDL.Record({
    'scoreValue' : IDL.Nat,
    'playerName' : IDL.Text,
    'gameType' : GameType,
  });
  
  return IDL.Service({
    'addFunFact' : IDL.Func([IDL.Text], [], []),
    'addScore' : IDL.Func([IDL.Text, IDL.Nat, GameType], [IDL.Text], []),
    'getAllFunFacts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFactByIndex' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getPlayerBestScore' : IDL.Func(
        [IDL.Text, GameType],
        [IDL.Opt(Score)],
        ['query'],
      ),
    'getTopScores' : IDL.Func([GameType], [IDL.Vec(Score)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };